title: Gopika PG # your name (or website title) here
logo: "/images/goplogo.jpg?raw=true"# your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am Energized by learning. I love to dig into data both in personal and professional life to find patterns and turn it into insight to solve problems. <br><br>
  Dedicated and detail-oriented Data Analyst. Eager to apply Analytic skills to Interpret data, analyze results and provide insight to determine operational impact, trends and opportunities.
  Proficient:Python, SQL, Excel, GoogleSheet, Machine Learning, HTML, CSS. <br><br>
  Novice:Javascript, Angular JS, Beautiful soup.<br><br>
  <a href="https://www.linkedin.com/in/gopikapg/">View My LinkedIn Profile</a> <br><br>
  <a href="https://public.tableau.com/app/profile/gopikaperkulam">Tableau Profile</a> <br><br>
  Certificates: Machine learning specialization, Google Analytics, Python.<br><br>
  Hobbies: Painting, Water bike, Badminton, Chess, Travelling.
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
